name: Dependabot auto-merge
on:
  pull_request_review:
    types:
      - submitted

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    name: Dependabot auto-merge
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' && github.event.review.state == 'approved' }}
    uses: hal-shu-sato/actions/.github/workflows/dependabot-auto-merge.yml@main
    with:
      pr_url: ${{ github.event.pull_request.html_url }}
      login: ${{ github.event.review.user.login }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
